### ISSUE TITLE
Does not output to a file

### ISSUE THREAD

**Issue by frankbolviken** [felthy/grunt-cachebuster#9]
`	cachebuster: {
		files: {
			'build/cachebusters.json': ['index.html']
		}
	},
`
I have this config in my Gruntfile.js.
The output when I run this task is:

Running "cachebuster:files" (cachebuster) task
Done, without errors.

But no file cachebusters.json is present.

Any tips?

**Comment by felthy** [comment]
You forgot to define a target (see docs for [configuring a multi-task](http://gruntjs.com/configuring-tasks#task-configuration-and-targets)):

``` javascript
cachebuster: {
    'default': {
        files: { 'build/cachebusters.json': ['index.html'] }
    }
}
```

You can replace the target name `'default'` with any name you like, but a name is mandatory.

``` bash
$ grunt cachebuster
Running "cachebuster:default" (cachebuster) task
Generating cachebuster file "build/cachebusters.json"...OK

Done, without errors.
```
